//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class InfoService
    {
        public int idInfoService { get; set; }
        public Nullable<int> idNameService { get; set; }
        public Nullable<int> MainImage { get; set; }
        public Nullable<int> Duration { get; set; }
        public Nullable<int> Price { get; set; }
        public Nullable<int> Descont { get; set; }
    
        public virtual Images Images { get; set; }
        public virtual NameService NameService { get; set; }
    }
}
